### ISSUE TITLE
uvm memory size subject to maxInternalRegReps

### ISSUE THREAD

**Issue by paulthilking** [Juniper/open-register-design-tool#24]
For memory arrays, the size should not be limited by maxInternalRegReps.

**Comment by sdnellen** [comment]
Added a max_internal_reg_reps systemverilog parameter to change this.  Made the message a warning except when generating rtl, where it will still throw an error (since v large internal reg arrays will result in decoder timing issues - generally these should be externals).  Change is in 170913.01 and will be picked up in next release.

**Comment by sdnellen** [comment]
update is in 170915.01.
